# Course 3 - Applied Machine Learning Using Python
## Assignment 2: Model Complexity, Generalization, and Regularization

### Overview
This assignment investigates the bias-variance tradeoff by exploring how model complexity affects training and test performance. Part 1 uses polynomial regression on synthetic data; Part 2 uses classification on the UCI Mushroom dataset.

### Learning Objectives
- Fit polynomial regression models of increasing degree and visualize underfitting vs overfitting
- Compute R-squared scores and identify the optimal polynomial degree
- Apply Lasso regularization to high-degree polynomial models
- Train a Decision Tree classifier and extract feature importances
- Use `validation_curve` with an SVM to tune the `gamma` hyperparameter

### Datasets
- **Part 1 (Regression):** Synthetic sinusoidal data, 15 points, generated with `np.random.seed(0)`
- **Part 2 (Classification):** `assets/mushrooms.csv` - UCI Mushroom dataset (edible vs poisonous), one-hot encoded with `pd.get_dummies`

### Assignment Structure
| Question | Part | Task |
|----------|------|------|
| Q1 | Regression | Fit polynomial models (degrees 1,3,6,9); return (4,100) prediction array |
| Q2 | Regression | Compute R^2 scores for degrees 0-9 on train and test sets |
| Q3 | Regression | Identify underfitting, overfitting, and best-generalization degree |
| Q4 | Regression | Compare LinearRegression vs Lasso (alpha=0.01) at degree 12 |
| Q5 | Classification | Top 5 features from a DecisionTreeClassifier on mushroom data |
| Q6 | Classification | Validation curve for SVM with gamma in [1e-4, 10] |
| Q7 | Classification | Identify underfitting, overfitting, and best gamma from Q6 |

---
_You are currently looking at **version 0.1** of this notebook._

# Assignment 2

In this assignment you'll explore the relationship between model complexity and generalization performance, by adjusting key parameters of various supervised learning models. Part 1 of this assignment will look at regression and Part 2 will look at classification.

## Part 1 - Regression

In [1]:
import numpy as np

np.random.randn(15)

array([ 1.90009681,  0.02920543, -1.07202893, -1.15304678, -2.71979642,
       -1.29720643, -0.18460124, -1.07962744,  0.56674017,  0.48334333,
       -0.62437383, -0.58399644, -0.29732098, -0.85551366,  1.79929427])

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


np.random.seed(0)
n = 15
x = np.linspace(0,10,n) + np.random.randn(n)/5
y = np.sin(x)+x/6 + np.random.randn(n)/10


X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=0)

def intro():
    %matplotlib notebook

    plt.figure()
    plt.scatter(X_train, y_train, label='training data')
    plt.scatter(X_test, y_test, label='test data')
    plt.legend(loc=4);

intro()

<IPython.core.display.Javascript object>

### What This Code Does
Generates synthetic training data: 15 points sampled along `y = sin(x) + x/6` with small Gaussian noise. The data simulates a non-linear relationship, making it a good benchmark for polynomial regression. `train_test_split` with no `test_size` argument uses the 75/25 default split.

### Question 1

Write a function that fits a polynomial LinearRegression model on the *training data* `X_train` for degrees 1, 3, 6, and 9. (Use PolynomialFeatures in sklearn.preprocessing to create the polynomial features and then fit a linear regression model) For each model, find 100 predicted values over the interval x = 0 to 10 (e.g. `np.linspace(0,10,100)`) and store this in a numpy array. The first row of this array should correspond to the output from the model trained on degree 1, the second row degree 3, the third row degree 6, and the fourth row degree 9.

<img src="assets/polynomialreg1.png" style="width: 1000px;"/>

The figure above shows the fitted models plotted on top of the original data (using `plot_one()`).

<br>
*This function should return a numpy array with shape `(4, 100)`*

In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

output_array = np.array([])
output_array.reshape(-1,100)
degree_predictions = np.zeros((4,100))
print(output_array.shape)
for thisDegree in [1,3,6,9]:
    poly_estimator = PolynomialFeatures(degree =thisDegree)
    #print(X_train)
    #print("Training sample reshaped into 2 D arrray \n", X_train.reshape(-1, 1) )
    X_train_polynomial_data = poly_estimator.fit_transform(X_train.reshape(-1, 1))
    #print("X_train_polynominal data: \n", X_train_polynomial_data)
    linearReg = LinearRegression()
    linearReg = linearReg.fit(X_train_polynomial_data, y_train)
    #print("R2 score on tthe polynomial trained data:",  linearReg.score(X_train_polynomial_data, y_train))
    data_for_prediction = np.linspace(0,10,100)
    #print(data_for_prediction)
    data_for_prediction = data_for_prediction.reshape(-1,1)
    poly_estimator2 = PolynomialFeatures(degree =thisDegree)
    data_for_prediction_poly =poly_estimator2.fit_transform(data_for_prediction)
    #print("Data to be used for prediction \n ", data_for_prediction_poly)
    prediction =linearReg.predict(data_for_prediction_poly)
    prediction = prediction.reshape(-1,100)
    #print(linearReg.predict(data_for_prediction))
    output_array = np.append(output_array, prediction)
    output_array =output_array.reshape(-1,100)
    #print(output_array)
degree_predictions = output_array
print(np.array_equal(degree_predictions, output_array))
degree_predictions.shape

(0,)
True


(4, 100)

In [4]:
def answer_one():
    from sklearn.linear_model import LinearRegression
    from sklearn.preprocessing import PolynomialFeatures
    
    degree_predictions = np.zeros((4,100))
    
    output_array = np.array([])
    output_array.reshape(-1,100)
    print(output_array.shape)
    for thisDegree in [1,3,6,9]:
        poly_estimator = PolynomialFeatures(degree =thisDegree)
        #print(X_train)
        #print("Training sample reshaped into 2 D arrray \n", X_train.reshape(-1, 1) )
        X_train_polynomial_data = poly_estimator.fit_transform(X_train.reshape(-1, 1))
        #print("X_train_polynominal data: \n", X_train_polynomial_data)
        linearReg = LinearRegression()
        linearReg = linearReg.fit(X_train_polynomial_data, y_train)
        #print("R2 score on tthe polynomial trained data:",  linearReg.score(X_train_polynomial_data, y_train))
        data_for_prediction = np.linspace(0,10,100)
        #print(data_for_prediction)
        data_for_prediction = data_for_prediction.reshape(-1,1)
        poly_estimator2 = PolynomialFeatures(degree =thisDegree)
        data_for_prediction_poly =poly_estimator2.fit_transform(data_for_prediction)
        #print("Data to be used for prediction \n ", data_for_prediction_poly)
        prediction =linearReg.predict(data_for_prediction_poly)
        prediction = prediction.reshape(-1,100)
        #print(linearReg.predict(data_for_prediction))
        output_array = np.append(output_array, prediction)
        output_array =output_array.reshape(-1,100)
        #print(output_array)
    degree_predictions = output_array
    return degree_predictions
    raise NotImplementedError()

In [5]:
# feel free to use the function plot_one() to replicate the figure 
# from the prompt once you have completed question one
def plot_one(degree_predictions):
    plt.figure(figsize=(10,5))
    plt.plot(X_train, y_train, 'o', label='training data', markersize=10)
    plt.plot(X_test, y_test, 'o', label='test data', markersize=10)
    for i,degree in enumerate([1,3,6,9]):
        plt.plot(np.linspace(0,10,100), degree_predictions[i], alpha=0.8, lw=2, label='degree={}'.format(degree))
    plt.ylim(-1,2.5)
    plt.legend(loc=4)

plot_one(answer_one())


(0,)


<IPython.core.display.Javascript object>

### Question 2

Write a function that fits a polynomial LinearRegression model on the training data `X_train` for degrees 0 through 9. For each model compute the $R^2$ (coefficient of determination) regression score on the training data as well as the the test data, and return both of these arrays in a tuple.

*This function should return a tuple of numpy arrays `(r2_train, r2_test)`. Both arrays should have shape `(10,)`*

In [6]:
def answer_two():
    from sklearn.linear_model import LinearRegression
    from sklearn.preprocessing import PolynomialFeatures
    from sklearn.metrics import r2_score

    r2_train = np.array([])
    r2_test = np.array([])
    
    # YOUR CODE HERE
    #from sklearn.linear_model import LinearRegression
    #from sklearn.preprocessing import PolynomialFeatures
    #from sklearn.metrics import r2_score

    #r2_train = np.array([])
    #r2_test = np.array([])

    print("Training Data before Polynomial tranformation:\n ", X_train)

    for thisDegree in range(10):
        #thisDegree =0
        poly_estimator = PolynomialFeatures(degree =thisDegree)
        #print(X_train)
        #print("Training sample reshaped into 2 D arrray \n", X_train.reshape(-1, 1) )
        X_train_polynomial_data = poly_estimator.fit_transform(X_train.reshape(-1, 1))


        linearReg = LinearRegression()
        linearReg = linearReg.fit(X_train_polynomial_data, y_train)
        #print("R2 score on tthe polynomial trained data:",  linearReg.score(X_train_polynomial_data, y_train))
        data_for_prediction = X_test
        #print(data_for_prediction)
        data_for_prediction = data_for_prediction.reshape(-1,1)
        poly_estimator2 = PolynomialFeatures(degree =thisDegree)
        data_for_prediction_poly =poly_estimator2.fit_transform(data_for_prediction)
        #print("Data to be used for prediction \n ", data_for_prediction_poly)
        prediction =linearReg.predict(data_for_prediction_poly)

        R2_train = linearReg.score(X_train_polynomial_data, y_train)
        R2_test = linearReg.score(data_for_prediction_poly, y_test)
        r2_train = np.append(r2_train, R2_train)        
        r2_test = np.append(r2_test, R2_test)
    print("R2 Training Data : \n", r2_train)
    print("R2 Test Data : \n", r2_test)
    print(r2_train.shape)
    a= (r2_train, r2_test)    
    print("Tuple with R2 square of Training Data and Test data : \n", a)
    return a
    raise NotImplementedError()

In [7]:
import matplotlib.pyplot as plt

R2_tuple = answer_two()
fig_1 = plt.figure(figsize = (6,6), dpi =100)
#axes_1 = (0.1, 0.1, 0.9,0.9)
#fig_1.add_axes(axes_1)
axes_1 = fig_1.subplots(nrows=1, ncols =1)
axes_1.plot(range(10), R2_tuple[0], 'r--', label = "R2 Square of Training Data", marker ='o')
axes_1.plot(range(10), R2_tuple[1], 'b--', label = "R2 Square of Test Data", marker ='o')
axes_1.set_xlabel("Degress of Polynomial")
axes_1.set_ylabel("R Squared Score")
axes_1.legend(loc =0)
train_array =R2_tuple[0]
test_array = R2_tuple[1]
for x in range(10):
    if train_array[x] > test_array[x]:
        print(x, "Overfitting")
    elif  train_array[x] < test_array[x]:
        print(x, "Underfitting")

#for x in range(10):
#    while train_array[x] < train_array[x+1]
    
        
x = (0,9,7)        

Training Data before Polynomial tranformation:
  [10.08877265  3.23065446  1.62431903  9.31004929  7.17166586  4.96972856
  8.14799756  2.59103578  0.35281047  3.375973    8.72363612]
R2 Training Data : 
 [0.         0.42924578 0.4510998  0.58719954 0.91941945 0.97578641
 0.99018233 0.99352509 0.99637545 0.99803706]
R2 Test Data : 
 [-0.47808642 -0.45237104 -0.06856984  0.00533105  0.73004943  0.87708301
  0.9214094   0.92021504  0.6324795  -0.64524777]
(10,)
Tuple with R2 square of Training Data and Test data : 
 (array([0.        , 0.42924578, 0.4510998 , 0.58719954, 0.91941945,
       0.97578641, 0.99018233, 0.99352509, 0.99637545, 0.99803706]), array([-0.47808642, -0.45237104, -0.06856984,  0.00533105,  0.73004943,
        0.87708301,  0.9214094 ,  0.92021504,  0.6324795 , -0.64524777]))


<IPython.core.display.Javascript object>

0 Overfitting
1 Overfitting
2 Overfitting
3 Overfitting
4 Overfitting
5 Overfitting
6 Overfitting
7 Overfitting
8 Overfitting
9 Overfitting


### Question 3

Based on the $R^2$ scores from question 2 (degree levels 0 through 9), what degree level corresponds to a model that is underfitting? What degree level corresponds to a model that is overfitting? What choice of degree level would provide a model with good generalization performance on this dataset? 

(Hint: Try plotting the $R^2$ scores from question 2 to visualize the relationship)

*This function should return a tuple with the degree values in this order: `(Underfitting, Overfitting, Good_Generalization)`*

In [8]:
def answer_three():
    # From the R^2 plot:
    # - Degree 0 has low train R^2 -> underfitting
    # - Degree 9 has high train but very low test R^2 -> overfitting
    # - Degree 6 has both high train and high test R^2 -> good generalization
    return (0, 9, 6)

answer_three()

(0, 9, 6)

### Question 4

Training models on high degree polynomial features can result in overfitting. Train two models: a non-regularized LinearRegression model and a Lasso Regression model (with parameters `alpha=0.01`, `max_iter=10000`, `tol=0.1`) on polynomial features of degree 12. Return the $R^2$ score for LinearRegression and Lasso model's test sets.

*This function should return a tuple `(LinearRegression_R2_test_score, Lasso_R2_test_score)`*

In [9]:
print(x)

(0, 9, 7)


In [10]:
# Exploratory cell: test polynomial degree 12 on train/test data (non-function version)
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Lasso, LinearRegression

poly = PolynomialFeatures(degree=12)
X_train_poly = poly.fit_transform(X_train.reshape(-1,1))
X_test_poly = poly.transform(X_test.reshape(-1,1))

lr = LinearRegression()
lr.fit(X_train_poly, y_train)
lr_score = lr.score(X_test_poly, y_test)

lasso = Lasso(alpha=0.01, max_iter=10000, tol=0.1)
lasso.fit(X_train_poly, y_train)
lasso_score = lasso.score(X_test_poly, y_test)

print("LinearRegression R2:", lr_score, "  Lasso R2:", lasso_score)

LinearRegression R2: -4.311980555741178   Lasso R2: 0.6051396919570099


In [11]:
def answer_four():
    from sklearn.preprocessing import PolynomialFeatures
    from sklearn.linear_model import Lasso, LinearRegression
    from sklearn.metrics import r2_score

    poly = PolynomialFeatures(degree=12)
    X_train_poly = poly.fit_transform(X_train.reshape(-1, 1))
    X_test_poly = poly.transform(X_test.reshape(-1, 1))

    # Non-regularized linear regression (prone to overfitting at degree 12)
    lr = LinearRegression()
    lr.fit(X_train_poly, y_train)
    lr_score = lr.score(X_test_poly, y_test)

    # Lasso regression adds L1 penalty to shrink coefficients -> better generalization
    lasso = Lasso(alpha=0.01, max_iter=10000, tol=0.1)
    lasso.fit(X_train_poly, y_train)
    lasso_score = lasso.score(X_test_poly, y_test)

    return (lr_score, lasso_score)

answer_four()

(-4.311980555741178, 0.6051396919570099)

## Part 2 - Classification

For this section of the assignment we will be working with the [UCI Mushroom Data Set](http://archive.ics.uci.edu/ml/datasets/Mushroom?ref=datanews.io) stored in `mushrooms.csv`. The data will be used to trian a model to predict whether or not a mushroom is poisonous. The following attributes are provided:

*Attribute Information:*

1. cap-shape: bell=b, conical=c, convex=x, flat=f, knobbed=k, sunken=s 
2. cap-surface: fibrous=f, grooves=g, scaly=y, smooth=s 
3. cap-color: brown=n, buff=b, cinnamon=c, gray=g, green=r, pink=p, purple=u, red=e, white=w, yellow=y 
4. bruises?: bruises=t, no=f 
5. odor: almond=a, anise=l, creosote=c, fishy=y, foul=f, musty=m, none=n, pungent=p, spicy=s 
6. gill-attachment: attached=a, descending=d, free=f, notched=n 
7. gill-spacing: close=c, crowded=w, distant=d 
8. gill-size: broad=b, narrow=n 
9. gill-color: black=k, brown=n, buff=b, chocolate=h, gray=g, green=r, orange=o, pink=p, purple=u, red=e, white=w, yellow=y 
10. stalk-shape: enlarging=e, tapering=t 
11. stalk-root: bulbous=b, club=c, cup=u, equal=e, rhizomorphs=z, rooted=r, missing=? 
12. stalk-surface-above-ring: fibrous=f, scaly=y, silky=k, smooth=s 
13. stalk-surface-below-ring: fibrous=f, scaly=y, silky=k, smooth=s 
14. stalk-color-above-ring: brown=n, buff=b, cinnamon=c, gray=g, orange=o, pink=p, red=e, white=w, yellow=y 
15. stalk-color-below-ring: brown=n, buff=b, cinnamon=c, gray=g, orange=o, pink=p, red=e, white=w, yellow=y 
16. veil-type: partial=p, universal=u 
17. veil-color: brown=n, orange=o, white=w, yellow=y 
18. ring-number: none=n, one=o, two=t 
19. ring-type: cobwebby=c, evanescent=e, flaring=f, large=l, none=n, pendant=p, sheathing=s, zone=z 
20. spore-print-color: black=k, brown=n, buff=b, chocolate=h, green=r, orange=o, purple=u, white=w, yellow=y 
21. population: abundant=a, clustered=c, numerous=n, scattered=s, several=v, solitary=y 
22. habitat: grasses=g, leaves=l, meadows=m, paths=p, urban=u, waste=w, woods=d

<br>

The data in the mushrooms dataset is currently encoded with strings. These values will need to be encoded to numeric to work with sklearn. We'll use pd.get_dummies to convert the categorical variables into indicator variables. 

### What This Code Does
Loads the mushroom dataset and applies one-hot encoding with `pd.get_dummies`. Since all mushroom features are categorical strings (e.g., 'cap-shape: bell=b'), they must be converted to numeric indicator variables before any sklearn model can be applied. The first two columns after encoding become the target (edible/poisonous), and all remaining columns are features.

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


mush_df = pd.read_csv('assets/mushrooms.csv')
mush_df2 = pd.get_dummies(mush_df)

X_mush = mush_df2.iloc[:,2:]
y_mush = mush_df2.iloc[:,1]


X_train2, X_test2, y_train2, y_test2 = train_test_split(X_mush, y_mush, random_state=0)

### Question 5

Using `X_train` and `y_train` from the preceeding cell, train a DecisionTreeClassifier with default parameters and random_state=0. What are the 5 most important features found by the decision tree?

*This function should return a list of length 5 of the feature names in descending order of importance.*

In [13]:
from sklearn.tree import DecisionTreeClassifier

decisionTree = DecisionTreeClassifier(random_state =0)
decisionTree = decisionTree.fit(X_train2, y_train2)
decisionTree.score(X_train2, y_train2)
print(decisionTree.feature_importances_)
#print(X_train2.columns)
key_features = decisionTree.feature_importances_[decisionTree.feature_importances_!=0]
#print(key_features)
sorted_array = sorted(key_features ,reverse = True)
#print(sorted_array)
index_values = np.argsort(decisionTree.feature_importances_)
index_values_reversed = list(index_values)
index_values_reversed.reverse()
index_values_top_5 = index_values_reversed[0:5]

#print('Index Values', index_values)
#print('Index Values Reversed', index_values_reversed)
#print(type(index_values_reversed))
print('Index Values Top 5', index_values_top_5)

print(type(index_values))

list_of_top_5_features=[]
for x in index_values_top_5:
    #print(X_train2.columns.values[x])
    list_of_top_5_features.append(X_train2.columns.values[x])
    #print(decisionTree.feature_importances_[x])
    
print(list_of_top_5_features)


[0.00000000e+00 6.55410817e-04 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 2.61653285e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.95090125e-02 0.00000000e+00
 0.00000000e+00 2.35036829e-02 0.00000000e+00 6.25143518e-01
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 3.71218849e-05 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.69175714e-01 0.00000000e+00 8.65891584e-02
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.37353673e-02
 0.00000000e+00 0.000000

In [14]:
def answer_five():
    from sklearn.tree import DecisionTreeClassifier
    
    # YOUR CODE HERE
    #from sklearn.tree import DecisionTreeClassifier

    decisionTree = DecisionTreeClassifier()
    decisionTree = decisionTree.fit(X_train2, y_train2)
    decisionTree.score(X_train2, y_train2)
    decisionTree.feature_importances_

    #key_features = decisionTree.feature_importances_[decisionTree.feature_importances_!=0]
    #sorted_array = sorted(key_features ,reverse = True)
    index_values = np.argsort(decisionTree.feature_importances_)[-5:]
    #print(index_values)

    list_of_top_5_features=[]
    for x in index_values:
        #print(X_train2.columns.values[x])
        list_of_top_5_features.append(X_train2.columns.values[x])
        #print(decisionTree.feature_importances_[x])
    print(list_of_top_5_features)
    return list_of_top_5_features
    raise NotImplementedError()

### Question 6

For this question, use the `validation_curve` function in `sklearn.model_selection` to determine training and test scores for a Support Vector Classifier (`SVC`) with varying parameter values.

Create an `SVC` with default parameters (i.e. `kernel='rbf', C=1`) and `random_state=0`. Recall that the kernel width of the RBF kernel is controlled using the `gamma` parameter.  Explore the effect of `gamma` on classifier accuracy by using the `validation_curve` function to find the training and test scores for 6 values of `gamma` from `0.0001` to `10` (i.e. `np.logspace(-4,1,6)`).

For each level of `gamma`, `validation_curve` will use 3-fold cross validation (use `cv=3, n_jobs=2` as parameters for `validation_curve`), returning two 6x3 (6 levels of gamma x 3 fits per level) arrays of the scores for the training and test sets in each fold.

Find the mean score across the five models for each level of `gamma` for both arrays, creating two arrays of length 6, and return a tuple with the two arrays.

e.g.

if one of your array of scores is

    array([[ 0.5,  0.4,  0.6],
           [ 0.7,  0.8,  0.7],
           [ 0.9,  0.8,  0.8],
           [ 0.8,  0.7,  0.8],
           [ 0.7,  0.6,  0.6],
           [ 0.4,  0.6,  0.5]])
       
it should then become

    array([ 0.5,  0.73333333,  0.83333333,  0.76666667,  0.63333333, 0.5])

*This function should return a tuple of numpy arrays `(training_scores, test_scores)` where each array in the tuple has shape `(6,)`.*

In [15]:
from sklearn.svm import SVC
from sklearn.model_selection import validation_curve

X_mush
y_mush

param_range = np.logspace(-4,1,6)

train_scores, test_scores = validation_curve(SVC(kernel = 'rbf', C=1), X_mush, y_mush, param_name = 'gamma',
               param_range = param_range, cv =3,n_jobs=2)
print("Training Scores:\n", train_scores)
print("Test Scores: \n ",test_scores)

train_scores_mean = np.mean(train_scores, axis=1)
test_scores_mean = np.mean(test_scores, axis=1)

print("Train Scores mean: \n ", train_scores_mean)
print("Test Scores mean: \n ", test_scores_mean)


Training Scores:
 [[0.93149926 0.91174298 0.85192024]
 [0.97913589 0.97895126 0.98504431]
 [0.99796898 0.99889217 1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]]
Test Scores: 
  [[0.82717873 0.87370753 0.96159527]
 [0.83493353 0.87370753 0.77991137]
 [0.8478582  0.96085672 0.71639586]
 [0.90546529 0.99002954 0.70199409]
 [0.86779911 0.94202363 0.69867061]
 [0.51772526 0.51809453 0.51809453]]
Train Scores mean: 
  [0.89838749 0.98104382 0.99895372 1.         1.         1.        ]
Test Scores mean: 
  [0.88749385 0.82951748 0.84170359 0.86582964 0.83616445 0.51797144]


In [16]:
def answer_six():
    from sklearn.svm import SVC
    from sklearn.model_selection import validation_curve
    # YOUR CODE HERE
    from sklearn.svm import SVC
    from sklearn.model_selection import validation_curve

    X_mush
    y_mush

    param_range = np.logspace(-4,1,6)

    train_scores, test_scores = validation_curve(SVC(kernel = 'rbf', C=1), X_mush, y_mush, param_name = 'gamma',
                   param_range = param_range, cv =3,n_jobs=2)
    #print("Training Scores:\n", train_scores)
    #print("Test Scores: \n ",test_scores)

    train_scores_mean = np.mean(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)

    #print("Train Scores mean: \n ", train_scores_mean)
    #print("Test Scores mean: \n ", test_scores_mean)
    return(train_scores_mean, test_scores_mean)

    raise NotImplementedError()

In [17]:
    param_range = np.logspace(-4,1,6)
    print(param_range)

[1.e-04 1.e-03 1.e-02 1.e-01 1.e+00 1.e+01]


### Question 7

Based on the scores from question 6, what gamma value corresponds to a model that is underfitting? What gamma value corresponds to a model that is overfitting? What choice of gamma would provide a model with good generalization performance on this dataset? 

(Hint: Try plotting the scores from question 6 to visualize the relationship)

*This function should return a tuple with the degree values in this order: `(Underfitting, Overfitting, Good_Generalization)`*

In [18]:
def answer_seven():
    # From validation_curve results:
    # - gamma=1e-4 (index 0): low training score -> underfitting
    # - gamma=10 (index 5): training=1.0, test~0.52 -> overfitting
    # - gamma=1e-3 (index 1): high test score ~0.83-0.89 -> good generalization
    return (1e-4, 10, 1e-3)

answer_seven()

(0.0001, 10, 0.001)

In [19]:
train_test_scores = answer_six()
train_scores = train_test_scores[0]
test_scores = train_test_scores[1]

#print(train_scores[1])
                                
for gamma in range(-4,1):
        print(gamma, train_scores[gamma], test_scores[gamma])
#x = ('Overfitting', 'Overfitting', 'Overfitting', 'Overfitting', 'Good_Generalization')        
x =(-4,-1,0)
#print(x)                                


-4 0.9989537173806008 0.8417035942885279
-3 1.0 0.8658296405711473
-2 1.0 0.836164451009355
-1 1.0 0.517971442639094
0 0.8983874938453965 0.8874938453963566
