In [1]:
# Regulator expression is a patter, which is provided to a processor along with some data
# Only 3 reasons why would want to do this
# 1. TO check if a pattern exists within some source data
# 2. To all the isntances of a complex pattern 
#3 Clean your source data using a pattern genrally through string splitting
# Regexes are not trivial. They are a foundational technique for data cleaning in data science applications 

In [3]:
# In this lecture, basic understanding of regexes
# How to define patterns for matching
# How to apply these patterns
# How to use the results of those patterns in data processing

In [4]:
# Import the re module
import re

# 1## Several main processing functions 
#1. match() - check for a match at the begining of a string and returns a boolean
#2 Search ()  - Check for a match anywhere in the string and return a boolean
#3 findall () will look for a pattern and pull out all occurences

In [35]:
text = "This is a good day."

if re.search("good", text):
    print("Wonderful!")
else: 
    print("Alas :(")
    


Wonderful!


In [37]:
re.search("^T", text)     #returns a match object

<re.Match object; span=(0, 1), match='T'>

In [38]:
re.match("T", text)

<re.Match object; span=(0, 1), match='T'>

In [6]:
# We can also segment a string, divide a string into tokens
text = "Amy works diligently. Amy gets good grades. Our student Amy is successful."
re.split("Amy", text) # Uses a pattern for creating a list of sub-strings

['',
 ' works diligently. ',
 ' gets good grades. Our student ',
 ' is successful.']

In [7]:
re.findall("Amy", text) #Looks for a pattern and pull out all occurences

['Amy', 'Amy', 'Amy']

# anchors - start of string
# Caret character - start of the string
# $  Dollar sign character means the end. 
text = "Amy works diligently. Amy gets good grades. Our student Amy is successful."
re.search("^Amy", text) #Returns an re match object An re match object always havs a boolean value and so can be evlauted in and if statement


In [9]:
#Lets create a string of single learners grades over a semester in one course across all their assignments

grades = "ACAAAABCBCBA"

In [11]:
# How many B's did the student get

len(re.findall("B", grades))

3

In [14]:
# find instances of all As or Bs 
# [] is a set, we are searaching for either A or B
re.findall ("[AB]", grades)

['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'A']

In [17]:
# [] is all called the set operator
# find out all grades that were not A

re.findall("[^A]", grades)

['C', 'B', 'C', 'B', 'C', 'B']

In [18]:
re.findall("^[^A]", grades)

[]

#### Quantifiers
    

In [21]:
re.findall("A{1,2}", grades)

['A', 'AA', 'AA', 'A']

In [23]:
re.findall("A{2,2}", grades)

['AA', 'AA']

In [24]:
re.findall("[AB]{1,2}", grades)

['A', 'AA', 'AA', 'B', 'B', 'BA']

In [34]:
re.findall("[A-Z]{1,2}", grades)

['AC', 'AA', 'AA', 'BC', 'BC', 'BA']

In [51]:
with open(r"C:\Users\singl\Applied Data Science -University of Michigan\Week_1_Files\Files\home\jovyan\work\resources\course1\week-1\datasets\ferpa.txt", mode = "r") as file:
#with open(r'C:\Users\singl\Applied Data Science -University of Michigan\Files\home\jovyan\work\resources\course1\week-1\datasets\mpg.csv') as csvfile:    
        wiki = file.read()
wiki

'Overview[edit]\nFERPA gives parents access to their child\'s education records, an opportunity to seek to have the records amended, and some control over the disclosure of information from the records. With several exceptions, schools must have a student\'s consent prior to the disclosure of education records after that student is 18 years old. The law applies only to educational agencies and institutions that receive funds under a program administered by the U.S. Department of Education.\n\nOther regulations under this act, effective starting January 3, 2012, allow for greater disclosures of personal and directory student identifying information and regulate student IDs and e-mail addresses.[2] For example, schools may provide external companies with a student\'s personally identifiable information without the student\'s consent.[2]\n\nExamples of situations affected by FERPA include school employees divulging information to anyone other than the student about the student\'s grades o

In [62]:
re.findall("[a-zA-Z]{1,100}\[edit\]", wiki)

['Overview[edit]', 'records[edit]', 'records[edit]']

In [63]:
#Headers all have the word edit and braces behind them
#\w can be used to match any letter including digits and numbers
# \w = metcharacter, indicates a special pattern of any letter or digit
# \s  matches any whitespace character
re.findall("[\w]{1,100}\[edit\]", wiki)

['Overview[edit]', 'records[edit]', 'records[edit]']

## Three other quantifiers, we can use which shorten up the curly brace syntax
#An asterix can be used to match 0 or more times



In [65]:
#Limit of searching for 1-100 characters removed by using asterix
re.findall("[\w]*\[edit\]", wiki)


['Overview[edit]', 'records[edit]', 'records[edit]']

In [66]:
#Add whitepsace to the set of acceptable chracters in the title 
re.findall("[\w ]*\[edit\]", wiki)

['Overview[edit]',
 'Access to public records[edit]',
 'Student medical records[edit]']

In [70]:
for title in re.findall("[\w ]*\[edit\]", wiki):
    print(title)
    print(re.split("[\[]", title)[0])

Overview[edit]
Overview
Access to public records[edit]
Access to public records
Student medical records[edit]
Student medical records


### Groups

In [71]:
#Till this point we have been taking about reg-ex as a single pattern which is matched

In [72]:
#groups are contained within paranthesis
re.findall("([\w ]*)(\[edit\])", wiki)

[('Overview', '[edit]'),
 ('Access to public records', '[edit]'),
 ('Student medical records', '[edit]')]

In [73]:
#labelling or naming groups. Labelling Groups is useful

# What is the correct regular expression to match a URL with letters, numbers, underscores and dots? A valid URL defined in this problem must meet the following requirements:

The URL consists of two or more strings made of letters, numbers, and underscores.
A dot is used in between the strings.
No two dots are allowed to appear consecutively.
For example, your regex should match URLs like: www.aBC.com, abc.com, ab_c.de8f.com
But your regex should not match: abc, abc..com

In [78]:
text = 'www.google_.com'

pattern = '[\w]*.[\w]*.[\w]{1,3}'

re.findall(pattern, text)




['www.google_.com']

In [81]:
# question 1
pattern = "^a|e|i|o|u[\w]*$[^a|e|i|o|u]"

test1 = 'unicorn'

re.findall(pattern, test1)


['i', 'o']

In [98]:
#Question 2

octal_pattern = "[0][ox][1-7]*"
hexadecimal_pattern = "[0][ox][1-9a-f]*"

pattern = octal_pattern|hexadecimal_pattern
print(pattern)
test1 = '0012f'

re.findall(pattern, test1)

TypeError: unsupported operand type(s) for |: 'str' and 'str'

In [109]:
#Question 3 

#Jane Doe is eating breakfast.
#Your regex should capture "Jane Doe".
#But in sentence
#Today is John Doe's birthday.

pattern = ''^[A-Z][a-z]*\\s[A-Z][a-z]*\\s"

test1 = 'L Zhang'
test 2 'Isaac Newton'

re.findall(pattern, test1)


SyntaxError: unexpected character after line continuation character (Temp/ipykernel_50324/4289517677.py, line 8)

In [132]:
#Question 4

pattern1 = "\$[1-9][0-9]*^."

pattern2 = "\$[1-9][0-9]*.[0-9][1-9]"

pattern = "(\$[1-9][0-9]*^.)(\$[1-9][0-9]*.[0-9][1-9])"

test1 = '$1000.1'
test2 = '$1.23'

re.findall(pattern, test1)

[]

In [133]:
pattern = (\d{4}-\d-\d{4}-\d)
pattern2 = (\d{3}-\d{3}-\d{3}-\d)

pattern = (\d{4}-\d-\d{4}-\d)|(\d{3}-\d{3}-\d{3}-\d)


SyntaxError: unexpected character after line continuation character (Temp/ipykernel_50324/2497219532.py, line 1)

In [157]:
def l2_dist(a, b):
    
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

import numpy as np 

c = np.array([[1,2], [3,4]])
d = np.array([[3,4], [5,6]])

print(c)
print(c.T)

np.reshape(c, (4,1),2)
c


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


TypeError: order must be str, not int

In [158]:
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)
print (a1)
print (a2)
print(a3)
print(a4)
print(a5)

[0.37229203 0.48258802 0.94830555 0.63034548]
[[0.16823401]
 [0.47459043]
 [0.61046591]
 [0.59144142]]
[[1 2 3 4]]
[1 2 3]
[1. 2. 3. 4.]


In [ ]:
np.random