In [1]:
import numpy as np

In [4]:
# Create an array by passing a list 
a  = np.array ([1,2,3])
a

array([1, 2, 3])

In [9]:
#Create a multi-dimenstional array by passing two lists 
a = np.array ([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#create an array using arange function
np.arange(start =1, stop =10, step = 1) 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(start = 1, stop = 5, step =0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9])

In [23]:
#linspace can be used to generate an array of floating point numbers. Stop is included in the array elements
a = np.linspace(start = 1, stop =4.9, num = 40)
a

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9])

In [35]:
b=np.array  ([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
b.shape

(2,)

In [34]:
c = np.array ([[1,2,3], [4,5,6]])
c
c.shape

(2, 3)

In [39]:
import random as rand

In [49]:
a = np.random.randn( 2,3)
a


array([[-0.48624789, -0.30016799,  1.00266278],
       [-0.23849073,  1.00741032,  0.70481841]])

In [50]:
a = np.zeros( 2,3)
print(a) 
b = np.ones( (2,3))
print(b)

TypeError: Cannot interpret '3' as a data type