In [3]:
import numpy as np
np.random.rand

<module 'numpy.random' from 'C:\\Users\\singl\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [12]:
a =np.random.rand(4,1)
a.shape
print(a)

[[0.85526235]
 [0.5100646 ]
 [0.64957275]
 [0.28887455]]


In [11]:

a =np.random.rand(4)
print(a)
a.shape

[0.85520594 0.92988336 0.50130964 0.36964629]


(4,)

In [17]:
a5 = np.linspace(1,4,4) 
print(a5)

[1. 2. 3. 4.]


In [18]:
a5.ndim

1

In [25]:
import re

string = "https://google.com"
string2 = "http://www.baidu.com"
pattern =  "(?<=[https]:\/\/)([A-Za-z0-9.]*)"

re.findall(pattern, string2)


['www.baidu.com']